// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List Projects",
  description: "List Sowmiyan's GitHub projects showcased on the portfolio (excludes hidden ones).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of projects to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const max = limit ?? 20;
    try {
      const [reposRes, hiddenRes] = await Promise.all([
        fetch("https://api.github.com/users/sowmiyan-s/repos?per_page=100&sort=updated"),
        (async () => {
          const supabase = createClient(
            process.env.SUPABASE_URL,
            process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
          );
          return supabase.from("hidden_projects").select("github_repo_id");
        })()
      ]);
      const repos = await reposRes.json();
      const hiddenIds = new Set((hiddenRes.data ?? []).map((r) => r.github_repo_id));
      const filtered = repos.filter((r) => !hiddenIds.has(r.id)).slice(0, max).map((r) => ({
        name: r.name,
        description: r.description,
        url: r.html_url,
        homepage: r.homepage,
        language: r.language,
        stars: r.stargazers_count,
        updated: r.updated_at
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
        structuredContent: { projects: filtered }
      };
    } catch (e) {
      return { content: [{ type: "text", text: `Error: ${e.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
var list_skills_default = defineTool2({
  name: "list_skills",
  title: "List Skills",
  description: "List Sowmiyan's technical and soft skills as shown on the portfolio.",
  inputSchema: {
    category: z2.enum(["tech", "non-tech", "all"]).optional().describe("Filter by category. Default 'all'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }) => {
    try {
      const supabase = createClient2(
        process.env.SUPABASE_URL,
        process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
      );
      let query = supabase.from("skills").select("name, category");
      if (category && category !== "all") query = query.eq("category", category);
      const { data, error } = await query;
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { skills: data ?? [] }
      };
    } catch (e) {
      return { content: [{ type: "text", text: `Error: ${e.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_profile_default = defineTool3({
  name: "get_profile",
  title: "Get Profile",
  description: "Get Sowmiyan S's professional profile: role, location, education, and contact links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Sowmiyan S",
      title: "AI Engineer \u2022 Full Stack Developer \u2022 Founder",
      tagline: "Building intelligent systems that scale.",
      location: "Namakkal, Tamil Nadu, India",
      education: "VSB College of Engineering Technical Campus, Kandampalayam",
      links: {
        portfolio: "https://pulse-profile-craft.lovable.app",
        github: "https://github.com/sowmiyan-s",
        resume: "https://drive.google.com/file/d/1NmangaAFo0eGT-KAsZi4VWOm6zI-KPk6/view?usp=sharing"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sowmiyan-portfolio-mcp",
  title: "Sowmiyan S Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools to query Sowmiyan S's portfolio: profile info, GitHub projects, and skills. Use `get_profile` for identity/contact, `list_projects` for showcased work, `list_skills` for capabilities.",
  tools: [list_projects_default, list_skills_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
